name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Java Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "20"

      - name: List Changed Files
        id: list_changed_files
        run: |
          echo "{files}={$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} )}" >> $GITHUB_OUTPUT

      - name: Run Javac
        run: |
          changed_files="${{ steps.list_changed_files.outputs.files }}"

          if [ -n "$changed_files" ]; then
          javac -d ./classes $changed_files
          else
          echo "No Java files changed."
          fi
